language: python

python:
  - "3.6"

#install dependences
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

#Run tests
script:
  - nosetests --with-coverage --cover-erase --cover-package=app

after_success:
  - coveralls
