language: python

python:
  - "3.6"

#install dependences
install:
  - pip install -r requirements.txt
  - pip install coveralls

#Run tests
script:
  - coverage run -m pytest -v app/tests/v1/test*

after_success:
  - coveralls
