language: python

env:
  - export DATABASE_URL='postgresql://postgres:postgres@localhost/fastfoodfast'
  - export DATABASE_TEST_URL='postgresql://postgres:postgres@localhost/fastfoodfast_testdb'
  - export FLASK_ENV='development'

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

services:
  - postgresql

addon:
  -postgresql: "9.6"

before_script:
  - psql -c "CREATE DATABASE fastfoodfast;" -U postgres
  - psql -c "CREATE USER promaster WITH PASSWORD 'postgres';" -U postgres

script:
  - nosetests --with-coverage --cover-package=app
  - coverage report

after_success:
  - coveralls
