language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

before_script:
  - psql -c 'create database fastfoodfast;' -U postgres
  - psql -c 'create database fastfoodfast_testdb;' -U postgres

script:
  - nosetests --with-coverage --cover-package=app/tests

after_success:
  - coveralls
