language: python

env:
  -export DATABASE_URL='postgresql://postgres:postgres@localhost/fastfoodfast'
  -export FLASK_ENV='development'

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

services:
  -postgresql

addon:
  -postgresql: "9.6"

before_script:
  -psql -c "create role postgres with superuser login password 'postgres';" -U postgres
  -psql -c 'create database fastfoodfast;' -U postgres
  -psql -c 'alter database fastfoodfast owner to postgres' -U postgres
  #
  # -psql -c 'CREATE DATABASE fastfoodfast' -u postgres
  # -psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA'

script:
  - nosetests --with-coverage --cover-package=app
  - coverage report

after_success:
  - coveralls
